build: Check if MSC package version has release notes.

diff --git a/multi-storage-client/justfile b/multi-storage-client/justfile
--- a/multi-storage-client/justfile
+++ b/multi-storage-client/justfile
@@ -10,6 +10,9 @@ compiler-targets := "aarch64-apple-darwin aarch64-unknown-linux-gnu x86_64-unkno
 # Default to the first Python binary on `PATH`.
 python-binary := "python"
 
+# MSC version.
+package-version := `uv version --short`
+
 # List recipes.
 help:
     just --list
@@ -44,6 +47,8 @@ analyze: prepare-toolchain
     if [[ -z "${CI:-}" ]]; then ruff check --fix; else ruff check --output-file .reports/ruff.json --output-format gitlab; fi
     # Type check.
     uv run pyright
+    # Check for release notes.
+    if [[ ! -s "../.release_notes/{{package-version}}.md" ]]; then echo "Missing {{package-version}} release notes!" && exit 1; fi
 
 # Stop storage systems.
 stop-storage-systems:
